# Generated by Django 5.1.1 on 2024-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIndicator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('surname', models.CharField(default='', max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='', max_length=5)),
                ('bmi', models.IntegerField()),
                ('is_smoke', models.IntegerField(default=0)),
                ('is_alco', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=0)),
                ('gluc', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
            ],
        ),
    ]
