# Generated by Django 5.1.1 on 2024-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patientindicator_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientindicator',
            old_name='bmi',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='patientindicator',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
