# Generated by Django 5.1.1 on 2024-11-17 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patientindicator_cholesterol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientindicator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientindicator',
            name='surname',
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='ap_hi',
            field=models.PositiveIntegerField(help_text='Systolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='ap_lo',
            field=models.PositiveIntegerField(help_text='Diastolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='cholesterol',
            field=models.FloatField(help_text='Cholesterol level'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='gluc',
            field=models.FloatField(help_text='Glucose level'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='height',
            field=models.PositiveIntegerField(help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='weight',
            field=models.FloatField(help_text='Weight in kg'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.profile'),
        ),
    ]
